In [1]:
import numpy as np

In [16]:
# First Approach
def vander(arr_1, N):
    return np.vander(arr_1,N)
arr_1 = np.array([1,2,4,6])
Y =4
vander(arr_1,Y)


array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [216,  36,   6,   1]])

In [28]:
# Second Approach
arr_1 = np.array([1,2,4,6])
Y =4
np.column_stack([arr_1**(Y-i-1) for i in range(Y)])

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [216,  36,   6,   1]], dtype=int32)

In [47]:
def moving_average(arr_1, m):
    return np.convolve(arr_1,np.ones(m), 'valid')/m
arr = np.array(list(map(int,input().split(' '))))
k =3
moving_average(arr,k)


3 5 7 2 8 10 11 65 72 81 99 100 150


array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])